disabled_rules:
- trailing_whitespace

opt_in_rules:
  - empty_count
  - empty_string
  # Performance rules (from CODING_CONVENTIONS.md lines 1105-1109)
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - first_where
  # Code smells (from CODING_CONVENTIONS.md lines 1111-1116)
  - unused_closure_parameter
  # Idiomatic Swift (from CODING_CONVENTIONS.md lines 1082-1089)
  - force_cast
  - force_try
  - force_unwrapping
  - implicit_getter
  - control_statement
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  # Best Practices (from CODING_CONVENTIONS.md lines 1097-1103)
  - implicit_optional_initialization
  - redundant_nil_coalescing
  - unused_enumerated
  - unused_optional_binding
  - vertical_parameter_alignment_on_call
  - vertical_whitespace

excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib
- DerivedData
- Generated
- .build
- "**/GeneratedAssetSymbols.swift"
- "**/Generated/**"
- "**/*.generated.swift"

line_length:
    warning: 200
    error: 300
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true

function_body_length:
    warning: 300
    error: 500

function_parameter_count:
    warning: 6
    error: 8

type_body_length:
    warning: 300
    error: 500

file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true

cyclomatic_complexity:
    warning: 15
    error: 25
    
identifier_name:
    min_length: 3
    max_length: 60
    excluded:
    - id  # Allow 'id' since it's commonly used in Swift (var id: UUID)
    allowed_symbols: []
    validates_start_with_lowercase: true

reporter: "xcode"
