name: CI - Build & Test (Composer)

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  build-and-test:
    name: Build and Test iOS App
    runs-on: macos-15
    timeout-minutes: 30
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.1.app/Contents/Developer
        
      - name: Verify Xcode Version
        run: |
          echo "=== Xcode Version ==="
          xcodebuild -version
          echo ""
          echo "=== Xcode Path ==="
          xcode-select -p
      
      - name: List Available Simulators
        run: |
          echo "=== All Available iOS Simulators ==="
          xcrun simctl list devices available iOS
          echo ""
          echo "=== iOS Runtimes ==="
          xcrun simctl list runtimes iOS
      
      - name: Show Valid Destinations
        run: |
          echo "=== Valid xcodebuild Destinations ==="
          xcodebuild -showdestinations \
            -project SequenceGame/SequenceGame.xcodeproj \
            -scheme SequenceGame | grep -i "iOS Simulator" || echo "No iOS Simulator destinations found"
      
      - name: Build Project
        run: |
          echo "=== Building Project ==="
          xcodebuild clean build \
            -project SequenceGame/SequenceGame.xcodeproj \
            -scheme SequenceGame \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.1' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            -derivedDataPath DerivedData
          
          echo "✅ Build successful!"
      
      - name: Run Tests
        run: |
          echo "=== Running Tests ==="
          xcodebuild test \
            -project SequenceGame/SequenceGame.xcodeproj \
            -scheme SequenceGame \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.1' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            -derivedDataPath DerivedData \
            -enableCodeCoverage YES \
            -resultBundlePath TestResults.xcresult \
            | tee test-output.log
          
          echo "✅ Tests completed!"
      
      - name: Check Test Results
        if: always()
        run: |
          if grep -q "Test Suite.*failed" test-output.log; then
            echo "❌ Tests failed"
            exit 1
          fi
          echo "✅ All tests passed"
      
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ github.sha }}
          path: |
            TestResults.xcresult
            test-output.log
            DerivedData/Logs/Test/*.xcresult

